replicaCount: 1

imagePullSecrets: []

service:
  type: ClusterIP
  annotations: {}

backend:
  apiUpstream: "http://hems-agent-backend"
  openvikingApiUpstream: "http://openviking:1933"

tls:
  enabled: false
  secretName: ""

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
  hosts:
    - host: agent-aws-dev.felicitysolar-shanghai.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
