ARG SH_NODE_IMAGE=docker.m.daocloud.io/library/node:20-alpine
ARG NGINX_IMAGE=docker.m.daocloud.io/library/nginx:1.27-alpine

FROM ${SH_NODE_IMAGE} AS builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM ${NGINX_IMAGE}

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/templates/default-http.conf
COPY nginx.ssl.conf /etc/nginx/templates/default-ssl.conf
COPY docker-entrypoint.d/40-select-default-conf.sh /docker-entrypoint.d/40-select-default-conf.sh
RUN chmod +x /docker-entrypoint.d/40-select-default-conf.sh

EXPOSE 80 443
STOPSIGNAL SIGQUIT
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
